-- CREATION D'UNE BASE DE DONNEES SUGGESTION 
CREATE DATABASE IF NOT EXISTS suggestions;
USE suggestions;
DROP TABLE IF EXISTS Messages;
CREATE TABLE Messages(
    id INT(10) UNIQUE AUTO_INCREMENT,
    Contenu TEXT COMMENT "Suggestions"
    )
ENGINE=INNODB;
